var jojo_sounds = {
	'yaredaze': 'yaredaze.mp3',
	'yareyaredaze': 'yaredaze.mp3',
	'muda': 'muda4.mp3',
	'ora': 'ora.mp3',
	'oraora': 'oradarby.mp3',
	//'oraoraora': 'ora206.mp3',
	'zawarudo': 'zawarudo2.mp3',
	'theworld': 'zawarudo2.mp3',
	'zawarudoeffect': 'zawarudosound.mp3',
	'theworldeffect': 'zawarudosound.mp3',
	'baseball': 'ohbaseball.mp3',
	'selectyourcar': 'serectcar.mp3',
	'serectyourcar': 'serectcar.mp3',
	'car': 'serectcar.mp3',
	'konodioda': 'konodio.mp3',
	'roadrollerda': 'roadroller.mp3',
	'roadroller': 'roadroller.mp3',
	'omg': 'omg2.mp3',
	'no': 'no4.mp3',
	'yes': 'yes6.mp3',
	'killdaho': 'killdaho.mp3',
	'hermitpurple': 'hermit.mp3',
	'ohno': 'ohno2.mp3',
	'jojo': 'joooojo.mp3',
	'joooojo': 'joooojo.mp3',
	'holyshit': 'holys.mp3',
	'goodbye': 'goodbye.mp3',
	'goodbyejojo': 'goodbye.mp3',
	'wry': 'WRYYYY.wav',
	'wryy': 'WRYYYY.wav',
	'wryyy': 'WRYYYY.wav',
	'wryyyy': 'WRYYYY.wav',
	'sonochinosadame': 'Sono.wav',
	'killerqueen': 'killerqueen.wav',
	'dora': 'dora.wav',
	'dorarara': 'dora.wav',
	'roundabout': 'roundabout.mp3',
	'tbc': 'roundabout.mp3',
	'tobecontinued': 'roundabout.mp3',
	'morioh': 'moriohcho.wav',
	'moriohcho': 'moriohcho.wav',
	'radio': 'moriohcho.wav',
	'doyouunderstand': 'do-you-understand.mp3',
	'understand': 'do-you-understand.mp3',
	'requiem': 'requiem.mp3',
	'koregarequiemda': 'requiem.mp3',
	'thisisrequiem': 'requiem.mp3'
}

var anime_sounds = {
	'stupid': 'stupid.mp3',
	'whatareyoustupid': 'stupid.mp3',
	'tirofinale': 'tirofinale.wav',
	'onepunch': 'punch.wav',
	'punch': 'punch.wav',
	'opm': 'opmtheme.wav',
	'nani': 'nani.mp3',
	'alreadydead': 'omae-wa-mou-shindeiru.mp3',
	'omae': 'omae-wa-mou-shindeiru.mp3',
	'omaewamoushindeiru': 'omae-wa-mou-shindeiru.mp3',
	'tutturu': 'tuturu.mp3',
	'fusrodah': 'fusrodah.wav'
}

var hots_sounds = {
	// Misc
	'dieinsects': 'RagnarosBase_Ultimate1Used02.mp3',
	'hatred': 'hatred.ogx',
	'notprepared': 'prepared.ogx',
	'nothingpersonal': 'Nova_Kill00.mp3',
	'nothingpersonnel': 'Nova_Kill00.mp3',
	'byfirebepurged': 'RagnarosBase_Ultimate2Used00.mp3',
	'byfire': 'RagnarosBase_Ultimate2Used00.mp3',
	'walkingcorpse': 'ValeeraBase_IntroResponse_Scourge00.mp3',
	'inquisition': 'WhitemaneBase_UI_Lockin00.ogg',
	'INQUISITION': 'WhitemaneBase_UI_Lockin00_fried.wav',
	'forazeroth': 'For_Azeroth.mp3',
	'leyline': 'LeyLine.mp3',

	// Stukov
	'sobeit': 'sobeit.wav',
	'stukovshove': 'StukovBase_Ultimate1UsedEnemy00.mp3',
	'stukovhadenough': 'StukovBase_Ultimate1Used01.mp3',
	'stukovmonster': 'StukovBase_Ultimate2Used02.mp3',
	'stukovpermission': 'StukovBase_IntroResponse_Dismissive00.mp3',
	'stukovdegenerate': 'StukovBase_IntroResponse_Degenerate00.mp3',
	'stukovfire': 'StukovBase_IntroResponse_Angry00.mp3',
	'stukovgoodtoseeyou': 'StukovBase_IntroQuestion_Positive00.mp3',
	'stukovsuffer': 'StukovBase_Attack02.mp3',
	'stukovwillnotdo': 'StukovBase_AI_Uhoh01.mp3',
	'stushove': 'StukovBase_Ultimate1UsedEnemy00.mp3',
	'stuenough': 'StukovBase_Ultimate1Used01.mp3',
	'stumonster': 'StukovBase_Ultimate2Used02.mp3',
	'stuperm': 'StukovBase_IntroResponse_Dismissive00.mp3',
	'studegen': 'StukovBase_IntroResponse_Degenerate00.mp3',
	'stufire': 'StukovBase_IntroResponse_Angry00.mp3',
	'stugood': 'StukovBase_IntroQuestion_Positive00.mp3',
	'stusuffer': 'StukovBase_Attack02.mp3',
	'stuwillnot': 'StukovBase_AI_Uhoh01.mp3',

	// Brightwing
	'brightwinglimbfromlimb': 'Brightwing_Pissed11.mp3',
	'brightwingeasytokill': 'Brightwing_KillSpreeEnd00.mp3',
	'brightwingsuffer': 'Brightwing_Kill03.mp3',
	'brightwingscaryvoice': 'Brightwing_IntroResponse_Abathur00.mp3',
	'brightwinghurtuntilyoudie': 'Brightwing_Attack06.mp3',
	'brightwinginsides': 'Brightwing_AI_Attack02.mp3',

	'bwlimbfromlimb': 'Brightwing_Pissed11.mp3',
	'bwhappy': 'Brightwing_Pissed11.mp3',
	'bweasy': 'Brightwing_KillSpreeEnd00.mp3',
	'bwsuffer': 'Brightwing_Kill03.mp3',
	'bwscaryvoice': 'Brightwing_IntroResponse_Abathur00.mp3',
	'bwhurt': 'Brightwing_Attack06.mp3',
	'bwinsides': 'Brightwing_AI_Attack02.mp3',

	// Alarak
	'alarakvictory': 'AlarakBase_Celebrate00.mp3',
	'alarakselection': 'AlarakBase_IntroResponse_Bizarre00.mp3',
	'alarakwit': 'AlarakBase_IntroResponse_Mocking00.mp3',
	'alarakwaste': 'AlarakBase_IntroResponse_Negative00.mp3',
	'alarakorificeflap': 'AlarakBase_IntroResponse_Terran00.mp3',
	'alarakdanger': 'AlarakBase_Ping_Danger00.mp3',
	'alarakyoucansee': 'AlarakBase_Ping_KillHero00.mp3',
	'alarakfreetoplay': 'AlarakBase_Pissed10.mp3',
	'alaraknotgood': 'AlarakBase_RepeatKill00.mp3',
	'alarakohitsyou': 'AlarakBase_RepeatKillMulti00.mp3',
	'alarakconsistent': 'AlarakBase_RepeatKillMulti01.mp3',
	'alarakreturned': 'AlarakBase_Revive01.mp3',
	'alaraktiresome': 'AlarakBase_Social_Goodbye00.mp3',
	'alarakdone': 'AlarakBase_Social_Goodbye01.mp3',
	'alarakyoumayspeak': 'AlarakBase_Social_Hello00.mp3',
	'alarakunworthy': 'AlarakBase_TeamKilled00.mp3',
	'alarakstopcrawlingback': 'AlarakBase_RepeatKillMulti02.mp3',
	'alarakacceptable': 'AlarakBase_Spec03.mp3',
	'alarakcurioschoice': 'AlarakBase_Spec04.mp3',
	'alarakexpected': 'AlarakBase_UI_ExLocked00.mp3',
	'alarakfinally': 'AlarakBase_UI_Lockin00.mp3',
	'alarakchain': 'AlarakBase_Yes04.mp3',
	'alarakwillit': 'AlarakBase_Yes00.mp3',
	'alarakpredictable': 'AlarakBase_Yes06.mp3',

	'alavictory': 'AlarakBase_Celebrate00.mp3',
	'alaselect': 'AlarakBase_IntroResponse_Bizarre00.mp3',
	'alawit': 'AlarakBase_IntroResponse_Mocking00.mp3',
	'alawaste': 'AlarakBase_IntroResponse_Negative00.mp3',
	'alaflap': 'AlarakBase_IntroResponse_Terran00.mp3',
	'aladanger': 'AlarakBase_Ping_Danger00.mp3',
	'alasee': 'AlarakBase_Ping_KillHero00.mp3',
	'alaftp': 'AlarakBase_Pissed10.mp3',
	'alanotgood': 'AlarakBase_RepeatKill00.mp3',
	'alaitsyou': 'AlarakBase_RepeatKillMulti00.mp3',
	'alaconsistent': 'AlarakBase_RepeatKillMulti01.mp3',
	'alareturned': 'AlarakBase_Revive01.mp3',
	'alatiresome': 'AlarakBase_Social_Goodbye00.mp3',
	'aladone': 'AlarakBase_Social_Goodbye01.mp3',
	'alamayspeak': 'AlarakBase_Social_Hello00.mp3',
	'alaunworthy': 'AlarakBase_TeamKilled00.mp3',
	'alastop': 'AlarakBase_RepeatKillMulti02.mp3',
	'alaaccept': 'AlarakBase_Spec03.mp3',
	'alachoice': 'AlarakBase_Spec04.mp3',
	'alaexpect': 'AlarakBase_UI_ExLocked00.mp3',
	'alafinally': 'AlarakBase_UI_Lockin00.mp3',
	'alachain': 'AlarakBase_Yes04.mp3',
	'alawillit': 'AlarakBase_Yes00.mp3',
	'alapredict': 'AlarakBase_Yes06.mp3'
}

var ff_sounds = {
	'sloppy': 'sloppy.mp3',
	'sickness': 'sickness-must-be-purged.mp3',
	'sicknessmustbepurged': 'sickness-must-be-purged.mp3',
	'purge': 'sickness-must-be-purged.mp3',
	'power': 'ffxiv-i-have-the-power.mp3',
	'filthyrats': 'ffxiv-filthy-rats.mp3',
	'rats': 'ffxiv-filthy-rats.mp3',
	'ultima': 'UnleashUltima.wav',
	'unleashultima': 'UnleashUltima.wav',
	'aggro': 'FFXIV_Aggro.mp3',
	'fullparty': 'FFXIV_Full_Party.mp3',
	'levelup': 'FFXIV_Level_Up.mp3',
	'limitbreak': 'FFXIV_Limit_Break_Activated.mp3',
	'lb': 'FFXIV_Limit_Break_Activated.mp3',
	'questaccepted': 'FFXIV_Quest_Accepted.mp3',
	'questcomplete': 'FFXIV_Quest_Complete.mp3'
}

var prequels_sounds = {
	'hellothere': 'HelloThere.wav',
	'hello': 'HelloThere.wav',
	'funbegins': 'FunBegins.mp3',
	'fun': 'FunBegins.mp3',
	'chosenone': 'ChosenOne.mp3',
	'unlimitedpower': 'power.mp3',
	'power': 'power.mp3'
}

var other_sounds = {
	'perfectshield': 'PerfectShield.mp3',
	'shield': 'PerfectShield.mp3',
	'sonicboom': 'SonicBoom.mp3',
	'robloxdeath': 'RobloxDeath.mp3',
	'oof': 'RobloxDeath.mp3'
}

module.exports = {
	"hots": hots_sounds,
	"jojo": jojo_sounds,
	"anime": anime_sounds,
	"ff": ff_sounds,
	"prequel": prequels_sounds,
	"other": other_sounds
}
