var jojo_sounds = {
	'yaredaze': 'yaredaze.ogg',
	'yareyaredaze': 'yaredaze.ogg',
	'muda': 'muda4.ogg',
	'ora': 'ora.ogg',
	'oraora': 'oradarby.ogg',
	//'oraoraora': 'ora206.ogg',
	'zawarudo': 'zawarudo2.ogg',
	'theworld': 'zawarudo2.ogg',
	'zawarudoeffect': 'zawarudosound.ogg',
	'theworldeffect': 'zawarudosound.ogg',
	'baseball': 'ohbaseball.ogg',
	'selectyourcar': 'serectcar.ogg',
	'serectyourcar': 'serectcar.ogg',
	'car': 'serectcar.ogg',
	'konodioda': 'konodio.ogg',
	'roadrollerda': 'roadroller.ogg',
	'roadroller': 'roadroller.ogg',
	'omg': 'omg2.ogg',
	'no': 'no4.ogg',
	'yes': 'yes6.ogg',
	'killdaho': 'killdaho.ogg',
	'hermitpurple': 'hermit.ogg',
	'ohno': 'ohno2.ogg',
	'jojo': 'joooojo.ogg',
	'joooojo': 'joooojo.ogg',
	'holyshit': 'holys.ogg',
	'goodbye': 'goodbye.ogg',
	'goodbyejojo': 'goodbye.ogg',
	'wry': 'WRYYYY.ogg',
	'wryy': 'WRYYYY.ogg',
	'wryyy': 'WRYYYY.ogg',
	'wryyyy': 'WRYYYY.ogg',
	'sonochinosadame': 'Sono.ogg',
	'killerqueen': 'killerqueen.ogg',
	'dora': 'dora.ogg',
	'dorarara': 'dora.ogg',
	'roundabout': 'roundabout.ogg',
	'tbc': 'roundabout.ogg',
	'tobecontinued': 'roundabout.ogg',
	'morioh': 'moriohcho.ogg',
	'moriohcho': 'moriohcho.ogg',
	'radio': 'moriohcho.ogg',
	'doyouunderstand': 'do-you-understand.ogg',
	'understand': 'do-you-understand.ogg',
	'requiem': 'requiem.ogg',
	'koregarequiemda': 'requiem.ogg',
	'thisisrequiem': 'requiem.ogg'
}

var anime_sounds = {
	'stupid': 'stupid.ogg',
	'whatareyoustupid': 'stupid.ogg',
	'tirofinale': 'tirofinale.ogg',
	'onepunch': 'punch.ogg',
	'punch': 'punch.ogg',
	'opm': 'opmtheme.ogg',
	'nani': 'nani.ogg',
	'alreadydead': 'omae-wa-mou-shindeiru.ogg',
	'omae': 'omae-wa-mou-shindeiru.ogg',
	'omaewamoushindeiru': 'omae-wa-mou-shindeiru.ogg',
	'tutturu': 'tuturu.ogg',
	'fusrodah': 'fusrodah.ogg'
}

var hots_sounds = {
	// Misc
	'dieinsects': 'RagnarosBase_Ultimate1Used02.ogg',
	'hatred': 'hatred.ogx',
	'notprepared': 'prepared.ogx',
	'nothingpersonal': 'Nova_Kill00.ogg',
	'nothingpersonnel': 'Nova_Kill00.ogg',
	'byfirebepurged': 'RagnarosBase_Ultimate2Used00.ogg',
	'byfire': 'RagnarosBase_Ultimate2Used00.ogg',
	'walkingcorpse': 'ValeeraBase_IntroResponse_Scourge00.ogg',
	'inquisition': 'WhitemaneBase_UI_Lockin00.ogg',
	'INQUISITION': 'WhitemaneBase_UI_Lockin00_fried.ogg',
	'forazeroth': 'For_Azeroth.ogg',
	'leyline': 'LeyLine.ogg',

	// Stukov
	'sobeit': 'sobeit.ogg',
	'stukovshove': 'StukovBase_Ultimate1UsedEnemy00.ogg',
	'stukovhadenough': 'StukovBase_Ultimate1Used01.ogg',
	'stukovmonster': 'StukovBase_Ultimate2Used02.ogg',
	'stukovpermission': 'StukovBase_IntroResponse_Dismissive00.ogg',
	'stukovdegenerate': 'StukovBase_IntroResponse_Degenerate00.ogg',
	'stukovfire': 'StukovBase_IntroResponse_Angry00.ogg',
	'stukovgoodtoseeyou': 'StukovBase_IntroQuestion_Positive00.ogg',
	'stukovsuffer': 'StukovBase_Attack02.ogg',
	'stukovwillnotdo': 'StukovBase_AI_Uhoh01.ogg',
	'stushove': 'StukovBase_Ultimate1UsedEnemy00.ogg',
	'stuenough': 'StukovBase_Ultimate1Used01.ogg',
	'stumonster': 'StukovBase_Ultimate2Used02.ogg',
	'stuperm': 'StukovBase_IntroResponse_Dismissive00.ogg',
	'studegen': 'StukovBase_IntroResponse_Degenerate00.ogg',
	'stufire': 'StukovBase_IntroResponse_Angry00.ogg',
	'stugood': 'StukovBase_IntroQuestion_Positive00.ogg',
	'stusuffer': 'StukovBase_Attack02.ogg',
	'stuwillnot': 'StukovBase_AI_Uhoh01.ogg',

	// Brightwing
	'brightwinglimbfromlimb': 'Brightwing_Pissed11.ogg',
	'brightwingeasytokill': 'Brightwing_KillSpreeEnd00.ogg',
	'brightwingsuffer': 'Brightwing_Kill03.ogg',
	'brightwingscaryvoice': 'Brightwing_IntroResponse_Abathur00.ogg',
	'brightwinghurtuntilyoudie': 'Brightwing_Attack06.ogg',
	'brightwinginsides': 'Brightwing_AI_Attack02.ogg',

	'bwlimbfromlimb': 'Brightwing_Pissed11.ogg',
	'bwhappy': 'Brightwing_Pissed11.ogg',
	'bweasy': 'Brightwing_KillSpreeEnd00.ogg',
	'bwsuffer': 'Brightwing_Kill03.ogg',
	'bwscaryvoice': 'Brightwing_IntroResponse_Abathur00.ogg',
	'bwhurt': 'Brightwing_Attack06.ogg',
	'bwinsides': 'Brightwing_AI_Attack02.ogg',

	// Alarak
	'alarakvictory': 'AlarakBase_Celebrate00.ogg',
	'alarakselection': 'AlarakBase_IntroResponse_Bizarre00.ogg',
	'alarakwit': 'AlarakBase_IntroResponse_Mocking00.ogg',
	'alarakwaste': 'AlarakBase_IntroResponse_Negative00.ogg',
	'alarakorificeflap': 'AlarakBase_IntroResponse_Terran00.ogg',
	'alarakdanger': 'AlarakBase_Ping_Danger00.ogg',
	'alarakyoucansee': 'AlarakBase_Ping_KillHero00.ogg',
	'alarakfreetoplay': 'AlarakBase_Pissed10.ogg',
	'alaraknotgood': 'AlarakBase_RepeatKill00.ogg',
	'alarakohitsyou': 'AlarakBase_RepeatKillMulti00.ogg',
	'alarakconsistent': 'AlarakBase_RepeatKillMulti01.ogg',
	'alarakreturned': 'AlarakBase_Revive01.ogg',
	'alaraktiresome': 'AlarakBase_Social_Goodbye00.ogg',
	'alarakdone': 'AlarakBase_Social_Goodbye01.ogg',
	'alarakyoumayspeak': 'AlarakBase_Social_Hello00.ogg',
	'alarakunworthy': 'AlarakBase_TeamKilled00.ogg',
	'alarakstopcrawlingback': 'AlarakBase_RepeatKillMulti02.ogg',
	'alarakacceptable': 'AlarakBase_Spec03.ogg',
	'alarakcurioschoice': 'AlarakBase_Spec04.ogg',
	'alarakexpected': 'AlarakBase_UI_ExLocked00.ogg',
	'alarakfinally': 'AlarakBase_UI_Lockin00.ogg',
	'alarakchain': 'AlarakBase_Yes04.ogg',
	'alarakwillit': 'AlarakBase_Yes00.ogg',
	'alarakpredictable': 'AlarakBase_Yes06.ogg',

	'alavictory': 'AlarakBase_Celebrate00.ogg',
	'alaselect': 'AlarakBase_IntroResponse_Bizarre00.ogg',
	'alawit': 'AlarakBase_IntroResponse_Mocking00.ogg',
	'alawaste': 'AlarakBase_IntroResponse_Negative00.ogg',
	'alaflap': 'AlarakBase_IntroResponse_Terran00.ogg',
	'aladanger': 'AlarakBase_Ping_Danger00.ogg',
	'alasee': 'AlarakBase_Ping_KillHero00.ogg',
	'alaftp': 'AlarakBase_Pissed10.ogg',
	'alanotgood': 'AlarakBase_RepeatKill00.ogg',
	'alaitsyou': 'AlarakBase_RepeatKillMulti00.ogg',
	'alaconsistent': 'AlarakBase_RepeatKillMulti01.ogg',
	'alareturned': 'AlarakBase_Revive01.ogg',
	'alatiresome': 'AlarakBase_Social_Goodbye00.ogg',
	'aladone': 'AlarakBase_Social_Goodbye01.ogg',
	'alamayspeak': 'AlarakBase_Social_Hello00.ogg',
	'alaunworthy': 'AlarakBase_TeamKilled00.ogg',
	'alastop': 'AlarakBase_RepeatKillMulti02.ogg',
	'alaaccept': 'AlarakBase_Spec03.ogg',
	'alachoice': 'AlarakBase_Spec04.ogg',
	'alaexpect': 'AlarakBase_UI_ExLocked00.ogg',
	'alafinally': 'AlarakBase_UI_Lockin00.ogg',
	'alachain': 'AlarakBase_Yes04.ogg',
	'alawillit': 'AlarakBase_Yes00.ogg',
	'alapredict': 'AlarakBase_Yes06.ogg'
}

var ff_sounds = {
	'sloppy': 'sloppy.ogg',
	'sickness': 'sickness-must-be-purged.ogg',
	'sicknessmustbepurged': 'sickness-must-be-purged.ogg',
	'purge': 'sickness-must-be-purged.ogg',
	'power': 'ffxiv-i-have-the-power.ogg',
	'filthyrats': 'ffxiv-filthy-rats.ogg',
	'rats': 'ffxiv-filthy-rats.ogg',
	'ultima': 'UnleashUltima.ogg',
	'unleashultima': 'UnleashUltima.ogg',
	'aggro': 'FFXIV_Aggro.ogg',
	'fullparty': 'FFXIV_Full_Party.ogg',
	'levelup': 'FFXIV_Level_Up.ogg',
	'limitbreak': 'FFXIV_Limit_Break_Activated.ogg',
	'lb': 'FFXIV_Limit_Break_Activated.ogg',
	'questaccepted': 'FFXIV_Quest_Accepted.ogg',
	'questcomplete': 'FFXIV_Quest_Complete.ogg'
}

var prequels_sounds = {
	'hellothere': 'HelloThere.ogg',
	'hello': 'HelloThere.ogg',
	'funbegins': 'FunBegins.ogg',
	'fun': 'FunBegins.ogg',
	'chosenone': 'ChosenOne.ogg',
	'unlimitedpower': 'power.ogg',
	'power': 'power.ogg'
}

var other_sounds = {
	'perfectshield': 'PerfectShield.ogg',
	'shield': 'PerfectShield.ogg',
	'sonicboom': 'SonicBoom.ogg',
	'robloxdeath': 'RobloxDeath.ogg',
	'oof': 'RobloxDeath.ogg'
}

module.exports = {
	"hots": hots_sounds,
	"jojo": jojo_sounds,
	"anime": anime_sounds,
	"ff": ff_sounds,
	"prequel": prequels_sounds,
	"other": other_sounds
}
